2015-09-28T03:38:01+00:00 ERR (3): 
exception 'Zend_Http_Client_Adapter_Exception' with message 'Unable to Connect to tcp://learn.magento.com:80. Error #0: php_network_getaddresses: getaddrinfo failed: 不知道这样的主机。 ' in C:\xampp\htdocs\magento\lib\Zend\Http\Client\Adapter\Socket.php:235
Stack trace:
#0 C:\xampp\htdocs\magento\lib\Zend\Http\Client.php(973): Zend_Http_Client_Adapter_Socket->connect('learn.magento.c...', 80, false)
#1 C:\xampp\htdocs\magento\lib\Zend\Oauth\Http\RequestToken.php(160): Zend_Http_Client->request()
#2 C:\xampp\htdocs\magento\lib\Zend\Oauth\Http.php(175): Zend_Oauth_Http_RequestToken->_attemptRequest(Array)
#3 C:\xampp\htdocs\magento\lib\Zend\Oauth\Http\RequestToken.php(51): Zend_Oauth_Http->startRequestCycle(Array)
#4 C:\xampp\htdocs\magento\lib\Zend\Oauth\Consumer.php(115): Zend_Oauth_Http_RequestToken->execute()
#5 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(136): Zend_Oauth_Consumer->getRequestToken()
#6 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(90): Vfeelit_RestConnect_Model_Oauth_Client->_getRequestTokenFromServer()
#7 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(49): Vfeelit_RestConnect_Model_Oauth_Client->getRequestToken()
#8 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\controllers\IndexController.php(18): Vfeelit_RestConnect_Model_Oauth_Client->authenticate()
#9 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Action.php(418): Vfeelit_RestConnect_IndexController->indexAction()
#10 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#11 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#12 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#13 C:\xampp\htdocs\magento\app\Mage.php(683): Mage_Core_Model_App->run(Array)
#14 C:\xampp\htdocs\magento\index.php(87): Mage::run('', 'store')
#15 {main}

Next exception 'Zend_Oauth_Exception' with message 'Error in HTTP request' in C:\xampp\htdocs\magento\lib\Zend\Oauth\Http.php:178
Stack trace:
#0 C:\xampp\htdocs\magento\lib\Zend\Oauth\Http\RequestToken.php(51): Zend_Oauth_Http->startRequestCycle(Array)
#1 C:\xampp\htdocs\magento\lib\Zend\Oauth\Consumer.php(115): Zend_Oauth_Http_RequestToken->execute()
#2 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(136): Zend_Oauth_Consumer->getRequestToken()
#3 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(90): Vfeelit_RestConnect_Model_Oauth_Client->_getRequestTokenFromServer()
#4 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(49): Vfeelit_RestConnect_Model_Oauth_Client->getRequestToken()
#5 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\controllers\IndexController.php(18): Vfeelit_RestConnect_Model_Oauth_Client->authenticate()
#6 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Action.php(418): Vfeelit_RestConnect_IndexController->indexAction()
#7 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#8 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#10 C:\xampp\htdocs\magento\app\Mage.php(683): Mage_Core_Model_App->run(Array)
#11 C:\xampp\htdocs\magento\index.php(87): Mage::run('', 'store')
#12 {main}
2015-09-28T06:10:47+00:00 ERR (3): 
exception 'Mage_Api2_Exception' with message 'Access denied' in C:\xampp\htdocs\magento\app\code\core\Mage\Api2\Model\Server.php:217
Stack trace:
#0 C:\xampp\htdocs\magento\app\code\core\Mage\Api2\Model\Server.php(106): Mage_Api2_Model_Server->_allow(Object(Mage_Api2_Model_Request), Object(Mage_Api2_Model_Auth_User_Guest))
#1 C:\xampp\htdocs\magento\api.php(67): Mage_Api2_Model_Server->run()
#2 {main}
2015-09-28T07:01:18+00:00 ERR (3): 
exception 'Zend_Http_Client_Adapter_Exception' with message 'Read timed out after 10 seconds' in C:\xampp\htdocs\magento\lib\Zend\Http\Client\Adapter\Socket.php:512
Stack trace:
#0 C:\xampp\htdocs\magento\lib\Zend\Http\Client\Adapter\Socket.php(330): Zend_Http_Client_Adapter_Socket->_checkSocketReadTimeout()
#1 C:\xampp\htdocs\magento\lib\Zend\Http\Client.php(989): Zend_Http_Client_Adapter_Socket->read()
#2 C:\xampp\htdocs\magento\lib\Zend\Oauth\Http\RequestToken.php(160): Zend_Http_Client->request()
#3 C:\xampp\htdocs\magento\lib\Zend\Oauth\Http.php(175): Zend_Oauth_Http_RequestToken->_attemptRequest(Array)
#4 C:\xampp\htdocs\magento\lib\Zend\Oauth\Http\RequestToken.php(51): Zend_Oauth_Http->startRequestCycle(Array)
#5 C:\xampp\htdocs\magento\lib\Zend\Oauth\Consumer.php(115): Zend_Oauth_Http_RequestToken->execute()
#6 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(136): Zend_Oauth_Consumer->getRequestToken()
#7 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(90): Vfeelit_RestConnect_Model_Oauth_Client->_getRequestTokenFromServer()
#8 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(49): Vfeelit_RestConnect_Model_Oauth_Client->getRequestToken()
#9 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\controllers\IndexController.php(18): Vfeelit_RestConnect_Model_Oauth_Client->authenticate()
#10 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Action.php(418): Vfeelit_RestConnect_IndexController->indexAction()
#11 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#12 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#13 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#14 C:\xampp\htdocs\magento\app\Mage.php(683): Mage_Core_Model_App->run(Array)
#15 C:\xampp\htdocs\magento\index.php(87): Mage::run('', 'store')
#16 {main}

Next exception 'Zend_Oauth_Exception' with message 'Error in HTTP request' in C:\xampp\htdocs\magento\lib\Zend\Oauth\Http.php:178
Stack trace:
#0 C:\xampp\htdocs\magento\lib\Zend\Oauth\Http\RequestToken.php(51): Zend_Oauth_Http->startRequestCycle(Array)
#1 C:\xampp\htdocs\magento\lib\Zend\Oauth\Consumer.php(115): Zend_Oauth_Http_RequestToken->execute()
#2 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(136): Zend_Oauth_Consumer->getRequestToken()
#3 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(90): Vfeelit_RestConnect_Model_Oauth_Client->_getRequestTokenFromServer()
#4 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\Model\OAuth\Client.php(49): Vfeelit_RestConnect_Model_Oauth_Client->getRequestToken()
#5 C:\xampp\htdocs\magento\app\code\local\Vfeelit\RestConnect\controllers\IndexController.php(18): Vfeelit_RestConnect_Model_Oauth_Client->authenticate()
#6 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Action.php(418): Vfeelit_RestConnect_IndexController->indexAction()
#7 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(250): Mage_Core_Controller_Varien_Action->dispatch('index')
#8 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Controller\Varien\Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 C:\xampp\htdocs\magento\app\code\core\Mage\Core\Model\App.php(354): Mage_Core_Controller_Varien_Front->dispatch()
#10 C:\xampp\htdocs\magento\app\Mage.php(683): Mage_Core_Model_App->run(Array)
#11 C:\xampp\htdocs\magento\index.php(87): Mage::run('', 'store')
#12 {main}
2015-09-28T07:15:59+00:00 ERR (3): 
exception 'Mage_Api2_Exception' with message 'Access denied' in C:\xampp\htdocs\magento\app\code\core\Mage\Api2\Model\Server.php:217
Stack trace:
#0 C:\xampp\htdocs\magento\app\code\core\Mage\Api2\Model\Server.php(106): Mage_Api2_Model_Server->_allow(Object(Mage_Api2_Model_Request), Object(Mage_Api2_Model_Auth_User_Guest))
#1 C:\xampp\htdocs\magento\api.php(67): Mage_Api2_Model_Server->run()
#2 {main}
2015-09-28T07:30:55+00:00 ERR (3): 
exception 'Mage_Api2_Exception' with message 'Access denied' in C:\xampp\htdocs\magento\app\code\core\Mage\Api2\Model\Server.php:217
Stack trace:
#0 C:\xampp\htdocs\magento\app\code\core\Mage\Api2\Model\Server.php(106): Mage_Api2_Model_Server->_allow(Object(Mage_Api2_Model_Request), Object(Mage_Api2_Model_Auth_User_Guest))
#1 C:\xampp\htdocs\magento\api.php(67): Mage_Api2_Model_Server->run()
#2 {main}
